# Generated by Django 5.0.6 on 2024-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
