# Generated by Django 5.0.6 on 2024-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_subscriptionprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=-1),
        ),
    ]
