# Generated by Django 5.0.6 on 2024-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_subscription_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
