# Generated by Django 5.0.6 on 2024-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_usersubscription_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="user_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
