# Generated by Django 5.0.6 on 2024-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0018_usersubscription_user_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="original_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
